on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

name: Build api and push to ECR

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Copy files to the test website with the AWS CLI
      run: echo "build complete"
      
  set:
    name: set
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Copy files to the test website with the AWS CLI
      run: echo "set version complete"
  
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: set
    if: always() && \
      (needs.set.result == 'skipped' || needs.set.result == 'success') \
      (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
    steps:
    - name: Copy files to the test website with the AWS CLI
      run: echo "deploy complete"
